baseURL = "https://teekamchandmandan.github.io"
languageCode = "en-us"
title = "Teekam Chand Mandan"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Teekam Chand Mandan"
    description = "Learner, Thinker, Solver"
    email = "teekamchandmandan@gmail.com"
    phone = "+91 8960009480"
    year = 2019
    avatar = "/images/teekam.jpeg"
    background = "/images/bg_head.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "May 26, 2019"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/teekamchandmandan"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/tcmandan"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/teekam"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/teekamchandmandan"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""

